CHAMPION_DATA = {
    # FORMAT: 'ChampionName': [DamageType, Primary Role, Class, Legacy Class, Early/Mid/Late/All]
    # My somewhat arbitrary "primary role" groupings:
    # Engage: Champions that start fights by landing key abilities
    # Pick: Champions that aim to pick off the primary carries before they can deal damage
    # Poke: Champions that aim to poke out the enemy team from range, forcing them to retreat before the fight can start
    # Sustain: Champions that enter fights and stay in them with healing or shielding
    # DPS: Champions that deal high damage, allowing them to become the primary damage dealers in large fights
    # CC: Champions that aim to crowd control the enemy, stopping them from dealing damage while protecting ally carries from threats (note this usually includes some form of counterengage to stop the enemy)
    # DoT: Champions that deal damage over time, allowing them to slowly wittle down the enemy champions
    # Support: Champions that support the fight by healing/shielding others
    # Tank: Champions that tank most of the damage from the enemy team
    'Aatrox': ['Physical/Max Health', 'Sustain', 'Juggernaut', 'Fighter', 'Mid/Late'],
    'Ahri': ['Magic/True Damage', 'Poke/Engage', 'Burst', 'Mage/Assassin', 'Early/Mid'],
    'Akali': ['Magic', 'Pick', 'Assassin', 'Assassin', 'Early/Mid'],
    'Akshan': ['Physical', 'Poke/DPS', 'Marksman/Assassin', 'Marksman/Assassin', 'All'],
    'Alistar': ['Magic', 'Engage/CC/Tank', 'Vanguard', 'Tank/Support', 'Early/Mid'],
    'Ambessa': ['Physical/Max Health', 'Engage/Pick/Sustain', 'Diver/Skirmisher', 'Fighter/Assassin', 'Early/Mid'],
    'Amumu': ['Magic/Max Health/True Damage', 'Engage/CC/Tank', 'Vanguard', 'Tank/Support', 'Mid'],
    'Anivia': ['Magic', 'Poke/DoT', 'Battlemage', 'Mage/Support', 'Mid/Late'],
    'Annie': ['Magic', 'Pick/Engage', 'Burst', 'Mage/Support', 'Mid'],
    'Aphelios': ['Physical', 'DPS', 'Marksman', 'Marksman', 'Late'],
    'Ashe': ['Physical', 'DPS/CC', 'Marksman', 'Marksman/Support', 'Mid/Late'],
    'Aurelion Sol': ['Magic/Max Health', 'DPS/DoT', 'Battlemage', 'Mage', 'Mid/Late'],
    'Aurora': ['Magic/Max Health', 'Poke/Engage', 'Burst/Assassin', 'Mage/Assassin', 'Early/Mid'],
    'Azir': ['Magic', 'Poke/Control', 'Specialist', 'Mage', 'Mid/Late'],
    'Bard': ['Magic', 'Engage/Poke/CC', 'Support', 'Support', 'Early/Mid'], 
    'Bel\'Veth': ['Physical/True Damage', 'DPS/Sustain', 'Skirmisher', 'Fighter', 'Mid/Late'],
    'Blitzcrank': ['Magic', 'Engage/Pick/CC', 'Catcher', 'Tank/Support', 'Early/Mid'],
    'Brand': ['Magic/Max Health', 'Poke/DoT', 'Burst', 'Mage/Support', 'All'],
    'Braum': ['Magic', 'Engage/CC/Tank', 'Warden', 'Tank/Support', 'Early/Mid'],
    'Briar': ['Physical', 'Sustain/Pick', 'Diver', 'Fighter/Assassin', 'Mid'],
    'Caitlyn': ['Physical', 'Poke/DPS', 'Marksman', 'Marksman', 'Early/Late'],
    'Camille': ['Physical/Max Health/True Damage', 'Engage/Pick', 'Diver', 'Fighter/Assassin', 'Early/Mid'],
    'Cassiopeia': ['Magic', 'Sustain/DPS', 'Battlemage', 'Mage', 'Mid/Late'],
    'Cho\'Gath': ['Magic/True Damage', 'Tank', 'Specialist', 'Tank/Mage', 'Late'],
    'Corki': ['Physical/True Damage', 'Poke/DPS', 'Marksman', 'Marksman/Mage', 'Mid/Late'],
    'Darius': ['Physical/True Damage', 'Sustain', 'Juggernaut', 'Fighter/Tank', 'Early'],
    'Diana': ['Magic', 'Engage/Pick', 'Assassin/Diver', 'Fighter/Assassin', 'Early/Mid'],
    'Dr. Mundo': ['Hybrid/Physical', 'Tank', 'Juggernaut', 'Tank/Fighter', 'Mid/Late'],
    'Draven': ['Physical', 'DPS', 'Marksman', 'Marksman', 'Early'],
    'Ekko': ['Magic', 'Pick', 'Assassin', 'Assassin/Mage', 'Mid'], 
    'Elise': ['Magic', 'Engage/Pick', 'Diver', 'Assassin/Mage', 'Early/Mid'],
    'Evelynn': ['Magic', 'Pick', 'Assassin', 'Assassin/Mage', 'Mid'],
    'Ezreal': ['Hybrid/Physical', 'Poke', 'Marksman', 'Marksman/Mage', 'Mid'],
    'Fiddlesticks': ['Magic', 'Engage/CC', 'Specialist', 'Mage/Support', 'Mid'],
    'Fiora': ['Physical/Max Health/True Damage', 'Sustain', 'Skirmisher', 'Fighter/Assassin', 'Mid/Late'],
    'Fizz': ['Magic', 'Pick', 'Assassin', 'Assassin/Fighter', 'Mid'],
    'Galio': ['Magic', 'Tank/CC', 'Warden', 'Tank/Mage', 'All'],
    'Gangplank': ['Physical/True Damage', 'Poke/Pick', 'Specialist', 'Fighter', 'Late'],
    'Garen': ['Physical/True Damage', 'Sustain/Pick', 'Juggernaut', 'Fighter/Tank', 'Early/Mid'],
    'Gnar': ['Physical/Max Health', 'Poke/Sustain/Engage', 'Specialist', 'Fighter/Tank', 'All'],
    'Gragas': ['Magic', 'Engage/Sustain', 'Vanguard', 'Fighter/Mage', 'All'],
    'Graves': ['Physical', 'DPS', 'Specialist', 'Marksman', 'Mid/Late'],
    'Gwen': ['Magic/True Damage', 'Sustain/Pick', 'Skirmisher', 'Fighter/Assassin', 'All'],
    'Hecarim': ['Physical', 'Engage/Sustain', 'Diver', 'Fighter/Tank', 'Mid'],
    'Heimerdinger': ['Magic', 'Poke/DoT', 'Specialist', 'Mage/Support', 'Early/Mid'],
    'Hwei': ['Magic', 'Poke/CC/DoT', 'Artillery', 'Mage/Support', 'All'],
    'Illaoi': ['Physical', 'Sustain/Tank', 'Juggernaut', 'Fighter/Tank', 'Early/Mid'], 
    'Irelia': ['Hybrid/Physical', 'Sustain/Engage/Pick', 'Diver', 'Fighter/Assassin', 'Mid'],
    'Ivern': ['Magic', 'Support', 'Catcher', 'Support/Mage', 'All'],
    'Janna': ['Magic', 'Support/CC', 'Enchanter', 'Support/Mage', 'Mid/Late'],
    'Jarvan IV': ['Physical', 'Engage/CC', 'Diver', 'Fighter/Tank', 'Early/Mid'],
    'Jax': ['Hybrid/Physical', 'Sustain', 'Skirmisher', 'Fighter/Assassin', 'Mid/Late'],
    'Jayce': ['Physical', 'Poke/DPS', 'Artillery', 'Fighter/Marksman', 'Early/Mid'],
    'Jhin': ['Physical', 'DPS/CC', 'Marksman/Catcher', 'Marksman/Mage', 'All'],
    'Jinx': ['Physical', 'DPS', 'Marksman', 'Marksman', 'Mid/Late'],
    'K\'Sante': ['Physical', 'Tank/Engage', 'Warden/Skirmisher', 'Tank/Fighter', 'All'],
    'Kai\'Sa': ['Hybrid', 'DPS', 'Marksman', 'Marksman/Mage', 'Mid/Late'],
    'Kalista': ['Physical/Max Health', 'DPS', 'Marksman', 'Marksman', 'Early/Mid'],
    'Karma': ['Magic', 'Poke/Support/CC', 'Burst/Enchanter', 'Mage/Support', 'Early/Mid'],
    'Karthus': ['Magic', 'DPS/DoT', 'Battlemage', 'Mage', 'Mid/Late'],
    'Kassadin': ['Magic', 'Sustain/Pick', 'Assassin', 'Assassin/Mage', 'Late'],
    'Katarina': ['Hybrid', 'Sustain/Pick', 'Assassin', 'Assassin/Mage', 'Mid'],
    'Kayle': ['Hybrid/Magic', 'DPS', 'Specialist', 'Mage/Marksman', 'Late'],
    'Kayn': ['Physical', 'Pick/Sustain', 'Skirmisher', 'Fighter/Assassin', 'Mid'], 
    'Kennen': ['Magic', 'Engage/CC', 'Specialist', 'Mage/Marksman', 'Mid'],
    'Kha\'Zix': ['Physical', 'Pick', 'Assassin', 'Assassin', 'Early/Mid'],
    'Kindred': ['Physical', 'DPS', 'Marksman', 'Marksman', 'Late'],
    'Kled': ['Physical', 'Engage/Sustain', 'Skirmisher', 'Fighter/Tank', 'Early/Mid'],
    'Kog\'Maw': ['Hybrid/Max Health', 'DPS/Poke', 'Marksman', 'Marksman/Mage', 'Late'],
    'LeBlanc': ['Magic', 'Poke/Pick', 'Burst/Assassin', 'Assassin/Mage', 'Early/Mid'], 
    'Lee Sin': ['Physical', 'Engage/Sustain', 'Diver', 'Fighter/Assassin', 'Early/Mid'],
    'Leona': ['Magic', 'Engage/CC/Tank', 'Vanguard', 'Tank/Support', 'Early/Mid'],
    'Lillia': ['Magic', 'Sustain/DoT', 'Skirmisher', 'Fighter/Mage', 'Mid/Late'],
    'Lissandra': ['Magic', 'Poke/CC/Pick', 'Burst', 'Mage', 'Mid'],
    'Lucian': ['Physical', 'DPS', 'Marksman', 'Marksman/Assassin', 'Early/Mid'],
    'Lulu': ['Magic', 'Support/CC', 'Enchanter', 'Support/Mage', 'Late'],
    'Lux': ['Magic', 'Poke/CC', 'Burst/Artillery', 'Mage/Support', 'All'],
    'Malphite': ['Magic', 'Engage/Tank/Pick', 'Vanguard', 'Tank/Mage', 'Mid'],
    'Malzahar': ['Magic', 'Poke/DoT/Engage', 'Battlemage', 'Mage/Assassin', 'Mid'],
    'Maokai': ['Magic', 'Engage/CC/Tank', 'Vanguard', 'Tank/Support', 'Early/Mid'],
    'Master Yi': ['Physical/True Damage', 'DPS', 'Skirmisher', 'Fighter/Assassin', 'Late'],
    'Mel': ['Magic', 'Support/CC', 'Enchanter', 'Support/Mage', 'Mid/Late'],
    'Milio': ['Magic', 'Poke/CC', 'Support', 'Support', 'Mid/Late'],
    'Miss Fortune': ['Physical', 'DPS', 'Marksman', 'Marksman/Mage', 'Early/Mid'], 
    'Mordekaiser': ['Magic', 'Sustain', 'Juggernaut', 'Fighter/Mage', 'Mid'],
    'Morgana': ['Magic', 'CC/DoT', 'Catcher', 'Support/Mage', 'All'],
    'Naafiri': ['Physical', 'Pick/Sustain', 'Assassin', 'Assassin/Fighter', 'Mid'],
    'Nami': ['Magic', 'Support/CC', 'Enchanter', 'Support/Mage', 'Early/Mid'],
    'Nasus': ['Physical/Magic', 'Sustain/DPS/Tank', 'Juggernaut', 'Fighter/Tank', 'Late'],
    'Nautilus': ['Magic', 'Engage/CC/Tank', 'Vanguard', 'Tank/Support', 'Early/Mid'],
    'Neeko': ['Magic', 'Engage/CC', 'Burst/Catcher', 'Mage/Support', 'Mid'],
    'Nidalee': ['Magic', 'Poke/Pick', 'Specialist', 'Assassin/Mage', 'Early/Mid'],
    'Nilah': ['Physical', 'DPS/Sustain', 'Skirmisher', 'Fighter/Assassin', 'Mid/Late'],
    'Nocturne': ['Physical', 'Pick/Sustain', 'Assassin', 'Fighter/Assassin', 'Mid'],
    'Nunu & Willump': ['Magic', 'Engage/CC/Tank', 'Vanguard', 'Tank/Mage', 'Early/Mid'],
    'Olaf': ['Physical', 'Sustain', 'Diver', 'Fighter/Tank', 'Early/Mid'],
    'Orianna': ['Magic', 'Poke/DPS', 'Burst', 'Mage/Support', 'Late'],
    'Ornn': ['Magic', 'Engage/CC/Tank', 'Vanguard', 'Tank/Fighter', 'Late'],
    'Pantheon': ['Physical', 'Pick/Engage', 'Diver', 'Fighter/Assassin', 'Early'],
    'Poppy': ['Physical', 'CC/Tank', 'Warden', 'Tank/Fighter', 'All'],
    'Pyke': ['Physical', 'Pick/Engage', 'Assassin/Catcher', 'Support/Assassin', 'Early/Mid'],
    'Qiyana': ['Physical', 'Pick', 'Assassin', 'Assassin/Fighter', 'Early/Mid'],
    'Quinn': ['Physical', 'Poke/Pick', 'Specialist', 'Marksman/Assassin', 'Early/Mid'],
    'Rakan': ['Magic', 'Engage/CC/Support', 'Catcher', 'Support', 'Early/Mid'],
    'Rammus': ['Magic', 'Engage/CC/Tank', 'Vanguard', 'Tank/Fighter', 'Early/Mid'],
    'Rek\'Sai': ['Physical/True Damage', 'Sustain', 'Diver', 'Fighter/Tank', 'Early/Mid'],
    'Rell': ['Magic', 'Engage/CC/Tank', 'Vanguard', 'Tank/Support', 'Early/Mid'],
    'Renata Glasc': ['Magic', 'Support/CC', 'Enchanter', 'Support/Mage', 'All'],
    'Renekton': ['Physical', 'Sustain', 'Diver', 'Fighter/Tank', 'Early/Mid'],
    'Rengar': ['Physical', 'Pick', 'Assassin/Diver', 'Assassin/Fighter', 'Mid'],
    'Riven': ['Physical', 'Sustain/Pick', 'Skirmisher', 'Fighter/Assassin', 'All'],
    'Rumble': ['Magic', 'Engage/DoT', 'Battlemage', 'Fighter/Mage', 'All'],
    'Ryze': ['Magic', 'DPS/Poke/CC', 'Battlemage', 'Mage/Fighter', 'Late'],
    'Samira': ['Physical', 'DPS/Sustain', 'Marksman', 'Marksman/Assassin', 'Mid/Late'],
    'Sejuani': ['Magic', 'Engage/CC/Tank', 'Vanguard', 'Tank/Fighter', 'Mid'],
    'Senna': ['Physical', 'DPS/Support', 'Marksman/Enchanter', 'Support/Marksman', 'Late'],
    'Seraphine': ['Magic', 'Poke/CC/Support', 'Burst/Enchanter', 'Support/Mage', 'Mid/Late'],
    'Sett': ['Physical', 'Sustain/Engage', 'Juggernaut', 'Fighter/Tank', 'Early/Mid'],
    'Shaco': ['Hybrid/Magic', 'Pick', 'Assassin', 'Assassin', 'Early/Mid'],
    'Shen': ['Hybrid', 'Tank/CC', 'Warden', 'Tank', 'All'],
    'Shyvana': ['Hybrid', 'Sustain/Poke', 'Juggernaut', 'Fighter/Mage', 'Mid'],
    'Singed': ['Magic', 'DoT/Sustain', 'Specialist', 'Tank/Mage', 'Mid'],
    'Sion': ['Physical', 'Engage/CC/Tank', 'Vanguard', 'Tank/Fighter', 'Late'],
    'Sivir': ['Physical', 'DPS', 'Marksman', 'Marksman', 'Mid/Late'],
    'Skarner': ['Physical', 'Engage/CC/Tank', 'Vanguard/Juggernaut', 'Tank/Fighter', 'Mid'],
    'Smolder': ['Physical/True Damage', 'DPS/Poke', 'Marksman', 'Marksman/Mage', 'Late'],
    'Sona': ['Magic', 'Poke/CC/Support', 'Enchanter', 'Support/Mage', 'Late'],
    'Soraka': ['Magic', 'Support', 'Enchanter', 'Support/Mage', 'Late'],
    'Swain': ['Magic', 'Sustain/DoT/CC', 'Battlemage', 'Mage/Support', 'Mid'],
    'Sylas': ['Magic', 'Sustain', 'Burst/Skirmisher', 'Mage/Assassin', 'Mid/Late'],
    'Syndra': ['Magic', 'DPS/CC', 'Burst', 'Mage', 'Late'],
    'Tahm Kench': ['Magic', 'Tank/CC', 'Warden', 'Tank/Support', 'Early/Mid'],
    'Taliyah': ['Magic', 'Poke/CC', 'Battlemage', 'Mage/Support', 'All'],
    'Talon': ['Physical', 'Pick', 'Assassin', 'Assassin', 'Early/Mid'],
    'Taric': ['Magic', 'Tank/CC/Support', 'Enchanter/Warden', 'Tank/Support', 'Mid/Late'],
    'Teemo': ['Magic', 'Poke/DoT', 'Specialist', 'Marksman/Mage', 'Early/Late'],
    'Thresh': ['Magic', 'Engage/Pick/CC', 'Catcher', 'Support/Tank', 'Early/Mid'],
    'Tristana': ['Physical', 'DPS', 'Marksman', 'Marksman/Assassin', 'Early/Late'],
    'Trundle': ['Physical', 'Sustain', 'Juggernaut', 'Fighter/Tank', 'All'],
    'Tryndamere': ['Physical', 'DPS/Sustain', 'Skirmisher', 'Fighter/Assassin', 'Early/Late'],
    'Twisted Fate': ['Magic/Physical', 'Poke/DPS/Pick', 'Burst', 'Mage/Marksman', 'All'],
    'Twitch': ['Physical/Magic', 'DPS', 'Marksman', 'Marksman/Assassin', 'Mid/Late'],
    'Udyr': ['Hybrid', 'Sustain', 'Juggernaut', 'Fighter/Tank', 'Early/Mid'],
    'Urgot': ['Physical', 'Sustain/DPS', 'Juggernaut', 'Fighter/Tank', 'Early/Mid'],
    'Varus': ['Hybrid/Max Health', 'Poke/DPS', 'Marksman/Artillery', 'Marksman/Mage', 'Mid/Late'],
    'Vayne': ['Physical/Max Health/True Damage', 'DPS', 'Marksman', 'Marksman/Assassin', 'Late'],
    'Veigar': ['Magic', 'DPS', 'Burst', 'Mage', 'Late'],
    'Vel\'Koz': ['Magic/True Damage', 'Poke/DoT', 'Artillery', 'Mage/Support', 'Early/Mid'],
    'Vex': ['Magic', 'Poke/CC/Engage', 'Burst', 'Mage', 'All'],
    'Vi': ['Physical', 'Engage/Sustain/Pick', 'Diver', 'Fighter/Assassin', 'Mid'],
    'Viego': ['Physical', 'Sustain/Pick', 'Skirmisher', 'Fighter/Assassin', 'Mid/Late'],
    'Viktor': ['Magic', 'Poke/DoT/DPS', 'Battlemage', 'Mage', 'Late'],
    'Vladimir': ['Magic', 'Sustain', 'Battlemage', 'Mage/Fighter', 'Late'],
    'Volibear': ['Hybrid', 'Sustain', 'Juggernaut', 'Fighter/Tank', 'Early/Mid'],
    'Warwick': ['Hybrid', 'Sustain', 'Diver', 'Fighter/Tank', 'Early/Mid'],
    'Wukong': ['Physical', 'Engage/Sustain', 'Diver', 'Fighter/Tank', 'Mid'],
    'Xayah': ['Physical', 'DPS', 'Marksman', 'Marksman', 'Mid/Late'],
    'Xerath': ['Magic', 'Poke', 'Artillery', 'Mage/Support', 'Early/Mid'],
    'Xin Zhao': ['Physical', 'Sustain/CC', 'Diver', 'Fighter/Tank', 'Early/Mid'],
    'Yasuo': ['Physical', 'DPS/Sustain', 'Skirmisher', 'Fighter/Assassin', 'All'],
    'Yone': ['Physical', 'DPS/Sustain', 'Assassin/Skirmisher', 'Fighter/Assassin', 'All'],
    'Yorick': ['Physical', 'Sustain/Tank', 'Juggernaut', 'Fighter/Tank', 'Mid'],
    'Yunara': ['Hybrid/Physical', 'DPS', 'Marksman', 'Marksman', 'Mid/Late'],
    'Yuumi': ['Magic', 'Support', 'Enchanter', 'Support/Mage', 'Mid/Late'],
    'Zaahen': ['Physical', 'Sustain', 'Skirmisher', 'Fighter/Assassin', 'Early/Mid'],
    'Zac': ['Magic', 'Engage/CC/Tank', 'Vanguard', 'Tank/Fighter', 'Mid'],
    'Zed': ['Physical', 'Pick', 'Assassin', 'Assassin', 'Early/Mid'],
    'Zeri': ['Physical/Magic', 'DPS', 'Marksman', 'Marksman', 'Mid/Late'],
    'Ziggs': ['Magic', 'Poke/DoT/DPS', 'Artillery', 'Mage', 'Early/Mid'],
    'Zilean': ['Magic', 'Support/CC/Poke', 'Specialist', 'Support/Mage', 'Mid/Late'],
    'Zoe': ['Magic', 'Poke/CC', 'Burst', 'Mage/Support', 'Mid'],
    'Zyra': ['Magic', 'Poke/CC', 'Catcher', 'Mage/Support', 'Early/Mid']
}